name: Simulation Test

on:
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  simulate:
    name: Simulation Smoke Test
    runs-on: ubuntu-latest
    # Taken from FRC 2412's 2026 codebase https://github.com/robototes/REBUILT2026/blob/main/.github/workflows/spotless.yml
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Automated sim test
        run: ./gradlew simulateJavaDebug -PautomatedTest=true
